# Generated by Django 4.2.14 on 2024-07-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_vendor_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
